# Game display settings
world:
  scale: 0.5
  width: 2880    # 5760 * scale
  height: 1620   # 3240 * scale
  frame_limit: 60 # fps
  title: "SFML game template tester"
  view:
    size_x: 960.0 # pixels. also the screen size 
    size_y: 540.0 # pixels. also the screen size  
    initial_center:
      x: 0.0 # pixels, absoloute from window
      y: 0.0 # pixels, absoloute from window

# Game score settings
score:
  initial: 0

# General animation settings
animation:
  change_time: 0.1 # seconds
  passthrough_offset: 65 # pixels

# General sprite and text settings
sprite:
  out_of_bounds_offset: 20 # pixels 
  out_of_bounds_adjustment: 30 # pixels 
  player_y_pos_bounds_run: 440  # SCREEN_HEIGHT - SPRITE_OUT_OF_BOUNDS_ADJUSTMENT

# Background settings
background:
  speed: 35.0 
  textures:
    day_path: "test/test-assets/sprites/png/background_night.png"
    night_path: "test/test-assets/sprites/png/background_day.png"
  position:
    x: -200.0 # pixels 
    y: 0.0 # pixels 
  scale:
    x: 1.0
    y: 1.0
  moving_direction: "RIGHT"

# Sprite paths
sprites:
  sprite1:
    speed: 100.0
    acceleration:
      x: 2.0 
      y: 2.0
    jump_acceleration: 
      x: 1.0
      y: 0.2
    index_max: 12 # number of total images for animation 
    animation_rows: 2 # number of rows for animation 
    path: "test/test-assets/sprites/png/player.png"
    position:
      x: 550.0 # pixels 
      y: 380.0 # pixels 
    scale:
      x: 1.0
      y: 1.0
  button1:
    index_max: 6 # number of animation frame
    path: "test/test-assets/sprites/png/Static.png"
    position:
      x: 0.0 # pixels 
      y: 0.0 # pixels 
    scale:
      x: 1.0
      y: 1.0
  cloudBlue:
    path: "test/test-assets/sprites/png/cloud1.png"
    position:
      x: 500.0 # pixels 
      y: 300.0 # pixels
    scale:
      x: 1.0
      y: 1.0
    speed: 10.0 
    acceleration:
      x: 2.0 
      y: 2.0
    respawn_time: 4.0 # seconds
    limit: 3 # number of clouds
  cloudPurple:
    path: "test/test-assets/sprites/png/cloud2.png"
    position:
      x: 700.0 # pixels 
      y: 300.0 # pixels
    respawn_time: 3.0 # seconds
    limit: 4 # number of clouds
  coin:
    path: "test/test-assets/sprites/png/coin.png"
    position:
      x: 100.0 # pixels 
      y: 100.0 # pixels
    scale:
      x: 1.0
      y: 1.0
    speed: 10.0 
    acceleration:
      x: 2.0 
      y: 2.0
    respawn_time: 8.0 # seconds
    limit: 5 # number of coins
    
# Tile settings
tiles:
  path: "test/test-assets/tiles/png/Tileset.png"
  rows: 6 # number of tiles in rows in tile map
  columns: 10 # number of tiles in columns in tile map
  number: 60 # total number of tiles 
  scale:
    x: 1.0
    y: 1.0
  tile_width: 32 # pixels 
  tile_height: 32 # pixels 

# Tile map settings
tilemap:
  position: 
    x: 0.0 # pixels
    y: 600.0 # pixels
  width: 140 # number of grids in a row 
  height: 2 # number of grids in a column 
  boundary_offset: 0 
  filepath: "test/test-assets/tiles/tilemap.txt"
  walkable: [false, true, true, false, false, true] #add more inside. if not meeting full size, the rest gets set to false 

# Text settings
text:
  size: 40 # pixels 
  font_path: "test/test-assets/fonts/ttf/font1.ttf"
  message: "Press space key to jump and WASD to move" # actual content in the text
  position:
    x: 100.0 # pixels 
    y: 200.0 # pixels 
  color: "YELLOW" # sf::Color 
ending_text:
  size: 40 # pixels 
  font_path: "test/test-assets/fonts/ttf/font1.ttf"
  message: "Game Over" # actual content in the text
  position:
    x: 200.0 # pixels 
    y: 200.0 # pixels 
  color: "RED" # sf::Color
score_text:
  size: 40 # pixels 
  font_path: "test/test-assets/fonts/ttf/font1.ttf"
  message: "Score: " # actual content in the text
  position:
    x: 500.0 # pixels 
    y: 100.0 # pixels 
  color: "CUSTOMCOLOR_LIGHTCORAL" # sf::Color

# Music settings
music:
  background_music:
    path: "test/test-assets/sound/mp3/music1.mp3"
    volume: 80.0 # percent
    ending_volume: 20.0 # percent
    loop: true

# Sound settings
sound:
  player_jump:
    path: "test/test-assets/sound/wav/jump.wav"
    volume: 90.0 # percent
  coin_hit:
    path: "test/test-assets/sound/wav/coin.wav"
    volume: 90.0 # percent
  button_click: 
    path: "test/test-assets/sound/wav/button.wav"
    volume: 90.0 # percent
  player_dead:
    path: "test/test-assets/sound/wav/playerDead.wav"
    volume: 90.0 # percent
